### ISSUE TITLE
Multiple Instances issue

### ISSUE THREAD

**Issue by Wiggin38** [mike-ward/tweetz#11]
Thank you for your work. A previous version of your app allowed me to have 3 separate instances running all logged into 3 separate Twitter accounts. When you restarted if I had a shortcut in the startup folder they would all login to the three separate accounts correctly. 
I am currently using 2.2.1 and originally made 3 separate folders with the self contained build with shortcuts to each folder renamed for each twitter account. Currently while I can have 3 different instances running from one exe if I restart they are all logged into one Twitter account and only one instance starts. 
Is this something that could be looked at or am I doing something wrong?

**Comment by mike-ward** [comment]
It was a happy accident if it worked that way before and not because I designed it into the app. That said, it seems like you just need to add three shortcuts in your startup folder instead of one if I'm understanding things. Make sure the `Start in` folders in your shortcuts point to the correct folders.

If that doesn't work, then rename the tweetz.core.exe files in each folder (tweetz.core.1.exe, .2.exe, .3.exe).

**Comment by Wiggin38** [comment]
Thank you I'll give that a try.

**Comment by Wiggin38** [comment]
Renaming the exe's worked. Thank you!
