### ISSUE TITLE
Adjusting window size

### ISSUE THREAD

**Issue by IlpoLeino** [mike-ward/tweetz#8]
It seems that it is now possible to change the window size only from bottom right corner.

This is a problem if you can´t reach that corner with your mouse. This happens regularly when i dock my laptop and no longer use laptop´s display. Resolution changes so that tweetz-window overlaps my main display that is connected to the docking station. Of course, i can restart my computer to get the correct size back but it would be easier to be able to just resize tweetz-window - from upper left corner perhaps...?

**Comment by mike-ward** [comment]
First off, thanks for the bug report. I'll explain below. If I sound snarky, it's not directed at you.

Down the rabbit hole we go...

There is an issue in WPF (or maybe Windows 10) where setting `WindowStyle=None` results in a thick white bar at the top of the window. 

The only way to remove the thick white bar is to set the window transparency to `true`, which disables the sizing borders. The only alternative to window sizing at that point is the window gripper in the lower right corner.

The reason Tweetz uses `WindowStyle=None` is it's the only reasonable way to add a custom titlebar in WPF. Yes, I know about the WindowChrome classes but they don't change title bars even though they are advertised to do so.

The reason for the custom title bar is because is the standard title bar turns white when the application does not have focus. Since the intent of Tweetz is to remain on screen, the white bar, especially when using the dark theme, is distracting/ugly.

There is no way to override the disabled color in a standard windows title bar.

I (and others) deemed it more important to have a title bar with a fixed color than sizing borders.

The sizing thumb in the lower right corner is part of the window chrome and can not be positioned elsewhere.

The only other option is to implement my own sizing logic. I did this before and it's a nightmare I don't wish to relive.

I've submitted an issue to Microsoft about this.

https://github.com/dotnet/wpf/issues/2435

If Microsoft ever resolves this issue, I'll restore the sizing borders.

I'll leave this issue open for future readers and further comments.

**Comment by mike-ward** [comment]
Found it! There's a workaround posted on [stackoverflow](https://stackoverflow.com/questions/611298/how-to-create-a-wpf-window-without-a-border-that-can-be-resized-via-a-grip-only/36258961#comment107218548_36258961) but it never worked for me.

The workaround did not work because I forgot to call a base class method in one of my mainwindow overrides. Problem solved, and cleanly. Will post a point release sometime soon.

**Comment by mike-ward** [comment]
Fix published in v2.1.1
